# Generated by Django 4.2.7 on 2023-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('complete', 'Complete')], max_length=10),
        ),
    ]
