# Generated by Django 4.2.7 on 2023-12-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_name', models.CharField(max_length=255)),
                ('donate_link', models.URLField()),
                ('donate_background_color', models.CharField(max_length=7)),
                ('donate_icon', models.CharField(max_length=50)),
                ('slide_image', models.ImageField(upload_to='slide_images/')),
                ('logo_image', models.ImageField(upload_to='logo_images/')),
            ],
        ),
    ]
