# Generated by Django 4.2.7 on 2023-12-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_websitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSettings',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
    ]
