# Generated by Django 5.0 on 2024-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_delete_websitesettings_remove_episode_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='anime_covers/')),
            ],
        ),
    ]
