# Generated by Django 5.0 on 2024-03-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_covers/'),
        ),
    ]
