# Generated by Django 5.0 on 2024-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_remove_movie_video_url_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
