# Generated by Django 4.1.5 on 2024-03-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_movie_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
