# Generated by Django 4.1.5 on 2024-03-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='anime.movie'),
            preserve_default=False,
        ),
    ]
