# Generated by Django 4.1.5 on 2024-03-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
    ]
