# Generated by Django 5.0.3 on 2024-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0021_alter_swipercontent_aksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipercontent',
            name='aksi',
            field=models.CharField(max_length=255),
        ),
    ]
